modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayTest="IGNORE_ALL_VERSION"
authors="Reiasu"
description='''
ReiParticleSkill gameplay module for NeoForge 1.21.x.
End dragon respawn effects, display and railgun commands run through ReiParticlesAPI runtime.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="reiparticlesapi"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="reiparticleskill.mixins.json"
